/*
    语法文档：https://www.w3cschool.cn/jenkins/jenkins-qc8a28op.html
    语法生成器：http://jenkins.dev.wh.digitalchina.com/job/dc.devops/pipeline-syntax/
*/
podTemplate(inheritFrom: 'pod1',
    containers:[
        //基础容器 不可删除
        containerTemplate(name:'jnlp',image:'harbor.dev.wh.digitalchina.com/devops/jenkins-slave-dev:latest')
        //添加需要的镜像容器
        //,containerTemplate(name:'maven',image:'harbor.dev.wh.digitalchina.com/library/maven:3-jdk-8',ttyEnabled:true,command:'cat')

    ],
    volumes:[
        hostPathVolume(hostPath:'/var/run/docker.sock',mountPath:'/var/run/docker.sock')
    ]
){
    node(POD_LABEL){    
        properties([gitLabConnection('newgitlab.digitalchina.com')])
        if(BRANCH_NAME == 'devops'){            
            gitlabBuilds(builds: ['Checkout','PushImage','Deploy']){
                stage 'Checkout'
                gitlabCommitStatus('Checkout'){
                    checkout scm
                }

                stage 'Push Image'
                gitlabCommitStatus('PushImage'){
                    def IMAGE_NAME = 'harbor.dev.wh.digitalchina.com/graduates-employment-reports/web-client:build-$BUILD_NUMBER'
                    def IMAGE = docker.build(IMAGE_NAME,'.')
                    withDockerRegistry(credentialsId:'xiaozlb-05361681-43b3-437c-aa2c-81e76827bd68',url:'https://harbor.dev.wh.digitalchina.com/'){ 
                        IMAGE.push()
                        sh 'docker rmi ' + IMAGE_NAME
                    }
                }  

                stage 'Deploy'
                //input(message:"部署到Rancher?", ok:"确定", submitter:"your itcode")
                gitlabCommitStatus('Deploy'){                
                    withCredentials([string(credentialsId: 'xiaozlb-25f391f8-d774-41f1-977d-24fd0fdd0dd1', variable: 'token')]) {
                        sh 'rancher login https://rancher.wh.digitalchina.com/ --token $token --skip-verify --context c-wsxm5:p-5hxcv'
                        //根据代码库中的deploy.yaml文件部署镜像
                        sh 'envsubst < Deploy.yaml | rancher kubectl apply -f -'
                    }
                }
            }
        }
        else{
            gitlabBuilds(builds: ['Checkout','Build','UnitTest','SonarTest']){
                stage 'Checkout'
                gitlabCommitStatus('Checkout'){
                    checkout scm
                }
                
                stage 'Build'
                gitlabCommitStatus('Build'){
                    echo 'Build'
                }
                
                stage 'Unit Test'
                gitlabCommitStatus('UnitTest'){
                    echo 'UnitTest'
                }                
                
                stage 'Sonar Test'
                gitlabCommitStatus('SonarTest'){
                    echo 'SonarTest'
                }
            } 
        }
    }
}